import type { Metadata } from 'next'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from '@/components/ui/sonner'
import { Suspense } from 'react'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <Suspense fallback={<div>Loading application</div>}>
            <ClerkProvider>
                <html lang="en">
                    <body className={`antialiased`}>
                        {children}
                        <Toaster />
                    </body>
                </html>
            </ClerkProvider>
        </Suspense>
    )
}
